### ISSUE TITLE
Quality of the result on the kindle

### ISSUE THREAD

**Issue by hannes101** [cheeberger/Economist2Epub#1]
Thanks a lot for starting this project, since a lot of people might be looking for this solution in the future. Could you perhaps share some experience on how it looks on the kindle?
How is the overall quality of the conversion? Especially regarding the text and the handling of the sections etc.

Thanks
hannes

**Comment by calebbrgr** [comment]
Sorry for the late reply, not very active on github. If you view the epub file on _Calibre_ you will see how each articles are stylized. I added a gif on the front page just as a project example. Did you manage to get it working?

**Comment by hannes101** [comment]
Thanks a lot, currently I am using the Pressreader.com subscription which I can access through my employer. But this actually might even look better than the export from there.
Although I get the current subscription for free :-)

**Comment by calebbrgr** [comment]
Yeah conversions to epub format can be tricky, I'm happy with how this turned out. Each article looks professional and neatly spaced. If you are still curious, each article is individually formatted as follows:
article1:
[main header]
[sub header]
[img]
[paragraphs]
article2:
[next main header (on new page)]
[...]

Enjoy your reading!
